name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t jondy483/reactapptest:latest .
      - name: Publish image to Docker Hub
        run: docker push jondy483/reactapptest:latest

  deploy:
    needs: build
    runs-on: self-hosted  # Adjust to match your EC2 runner label##@
    steps:
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull image from Docker Hub
        run: docker pull jondy483/reactapptest:latest
      - name: Delete old container (if exists)
        run: docker rm -f nodejs-app-container || true
      - name: Run Docker container
        run: docker run -d -p 8080:3000 --name nodejs-app-container jondy483/reactapptest:latest
        